W&B disabled.
task start
Use seed 3
Traceback (most recent call last):
  File "/lustre04/scratch/qianxi/sparse_training/dec_must/must_env/lib/python3.8/site-packages/numpy/core/_internal.py", line 649, in _dtype_from_pep3118
    def _dtype_from_pep3118(spec):
KeyboardInterrupt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "wrappers.pxi", line 4707, in mujoco_py.cymj._wrap_char_1d
ValueError: 'c' is not a valid PEP 3118 buffer format string
Exception ignored in: 'mujoco_py.cymj.PyMjModel._set'
Traceback (most recent call last):
  File "wrappers.pxi", line 4707, in mujoco_py.cymj._wrap_char_1d
ValueError: 'c' is not a valid PEP 3118 buffer format string
2023-12-04 21:31:06,920 MainThread INFO: Experiment Name:1125_itv50_pr0.5_sllr1e-4_slloss1_trajinfo1_selected2
2023-12-04 21:31:06,921 MainThread INFO: {
  "env_name": "mt10",
  "selected_task_amount": 2,
  "env": {
    "reward_scale": 1,
    "obs_norm": false
  },
  "meta_env": {
    "obs_type": "with_goal_and_id"
  },
  "replay_buffer": {
    "size": 1000000.0
  },
  "net": {
    "hidden_shapes": [
      400,
      400,
      400
    ]
  },
  "task_embedding": {
    "em_hidden_shapes": [
      256,
      128
    ]
  },
  "traj_encoder": {
    "latent_size": 256
  },
  "generator": {
    "one_hot_mlp_hidden": 64,
    "generator_mlp_hidden": 256,
    "one_hot_result_dim": 64
  },
  "sparse_training": {
    "pruning_ratio": 0.5
  },
  "general_setting": {
    "discount": 0.99,
    "pretrain_epochs": 20,
    "num_epochs": 10000,
    "epoch_frames": 150,
    "max_episode_frames": 150,
    "generator_lr": 0.0001,
    "batch_size": 1280,
    "min_pool": 10000,
    "success_traj_update_only": true,
    "target_hard_update_period": 1000,
    "use_soft_update": true,
    "tau": 0.005,
    "opt_times": 200,
    "update_end_epoch": 10000,
    "mask_update_interval": 50,
    "eval_episodes": 3,
    "recent_traj_window": 10,
    "sl_optim_times": 5,
    "use_trajectory_info": 1,
    "use_sl_loss": 1
  },
  "sac": {
    "plr": 0.0001,
    "qlr": 0.0001,
    "reparameterization": true,
    "automatic_entropy_tuning": true,
    "policy_std_reg_weight": 0,
    "policy_mean_reg_weight": 0
  }
}
/lustre04/scratch/qianxi/sparse_training/dec_must/must_env/lib/python3.8/site-packages/gym/logger.py:30: UserWarning: [33mWARN: Could not seed environment <MTEnv instance>[0m
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
finish policy net init
Traceback (most recent call last):
  File "starter/mt_must_sac.py", line 397, in <module>
    experiment(args)
  File "starter/mt_must_sac.py", line 189, in experiment
    encoder = networks.TrajectoryEncoder(env.observation_space.shape[0],
  File "/lustre04/scratch/qianxi/sparse_training/dec_must/DST_RL/./torchrl/networks/trajectory_encoder.py", line 32, in __init__
    th.zeros(latent_dim).to(device),
KeyboardInterrupt
